name: dwi_temperature
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - nibabel
  - ants  # For bias field correction in MRtrix3
  - pip
  - pip:
    - argparse